In [2]:
import pandas as pd

In [3]:

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
titanic_df = pd.read_csv(url)

In [5]:
titanic_df.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
620,621,0,3,"Yasbeck, Mr. Antoni",male,27.0,1,0,2659,14.4542,NaN,C
272,273,1,2,"Mellinger, Mrs. (Elizabeth Anne Maidment)",female,41.0,0,1,250644,19.5000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
37,38,0,3,"Cann, Mr. Ernest Charles",male,21.0,0,0,A./5. 2152,8.0500,NaN,S
339,340,0,1,"Blackwell, Mr. Stephen Weart",male,45.0,0,0,113784,35.5000,T,S
649,650,1,3,"Stanley, Miss. Amy Zillah Elsie",female,23.0,0,0,CA. 2314,7.5500,NaN,S
599,600,1,1,"Duff Gordon, Sir. Cosmo Edmund (""Mr Morgan"")",male,49.0,1,0,PC 17485,56.9292,A20,C
615,616,1,2,"Herman, Miss. Alice",female,24.0,1,2,220845,65.0000,NaN,S
635,636,1,2,"Davis, Miss. Mary",female,28.0,0,0,237668,13.0000,NaN,S

In [6]:
titanic_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
# cabin ==drop
# age=simple imputer
# sex=ordinal encoding
# embarked=OHE
# pclass=ohe
# Then create new dataset from this

In [10]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [13]:

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df = pd.read_csv(url)

In [25]:
from sklearn.model_selection import train_test_split

# Separate features and target variable
X = df.drop(columns=['Cabin', 'PassengerId'])
y = df['Survived']  # Replace 'target_column' with the name of your target variable

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [27]:
# Adding simple imputer to age

In [28]:
si=SimpleImputer()
xtrainaage=si.fit_transform(x_train[['Age']])

xtestage=si.fit_transform(x_test[['Age']])

xtestage.shape

(357, 1)

array([[30.31620209],
       [31.        ],
       [20.        ],
       [ 6.        ],
       [14.        ],
       [26.        ],
       [30.31620209],
       [16.        ],
       [16.        ],
       [19.        ],
       [37.        ],
       [44.        ],
       [30.31620209],
       [30.        ],
       [36.        ],
       [16.        ],
       [42.        ],
       [30.31620209],
       [27.        ],
       [47.        ],
       [24.        ],
       [34.        ],
       [19.        ],
       [20.        ],
       [30.31620209],
       [10.        ],
       [40.        ],
       [31.        ],
       [ 4.        ],
       [31.        ],
       [19.        ],
       [22.        ],
       [30.31620209],
       [30.31620209],
       [18.        ],
       [27.        ],
       [28.        ],
       [30.31620209],
       [30.        ],
       [30.31620209],
       [21.        ],
       [29.        ],
       [30.31620209],
       [30.31620209],
       [45.        ],
       [16.        ],
       [19.        ],
       [23.        ],
       [24.        ],
       [58.        ],
       [ 5.        ],
       [52.        ],
       [40.        ],
       [11.        ],
       [65.        ],
       [18.        ],
       [32.        ],
       [50.        ],
       [35.        ],
       [19.        ],
       [21.        ],
       [13.        ],
       [28.        ],
       [30.31620209],
       [30.31620209],
       [57.        ],
       [21.        ],
       [29.        ],
       [17.        ],
       [52.        ],
       [26.        ],
       [18.        ],
       [26.        ],
       [39.        ],
       [23.        ],
       [36.        ],
       [30.5       ],
       [22.        ],
       [38.        ],
       [41.        ],
       [16.        ],
       [29.        ],
       [40.        ],
       [30.31620209],
       [56.        ],
       [71.        ],
       [31.        ],
       [30.        ],
       [38.        ],
       [30.31620209],
       [ 9.        ],
       [ 9.        ],
       [61.        ],
       [30.31620209],
       [30.31620209],
       [28.        ],
       [48.        ],
       [45.        ],
       [36.        ],
       [27.        ],
       [64.        ],
       [35.        ],
       [19.        ],
       [38.        ],
       [30.5       ],
       [25.        ],
       [40.        ],
       [47.        ],
       [30.        ],
       [40.        ],
       [30.31620209],
       [20.5       ],
       [30.31620209],
       [36.        ],
       [30.31620209],
       [20.        ],
       [71.        ],
       [36.        ],
       [22.        ],
       [48.        ],
       [23.        ],
       [32.        ],
       [63.        ],
       [ 0.83      ],
       [25.        ],
       [35.        ],
       [49.        ],
       [24.        ],
       [30.31620209],
       [21.        ],
       [30.31620209],
       [30.31620209],
       [30.31620209],
       [ 5.        ],
       [49.        ],
       [15.        ],
       [30.31620209],
       [29.        ],
       [42.        ],
       [18.        ],
       [21.        ],
       [44.        ],
       [28.        ],
       [37.        ],
       [39.        ],
       [34.        ],
       [30.        ],
       [66.        ],
       [30.31620209],
       [43.        ],
       [30.31620209],
       [24.        ],
       [18.        ],
       [30.31620209],
       [30.31620209],
       [30.31620209],
       [30.31620209],
       [30.31620209],
       [36.        ],
       [32.        ],
       [23.5       ],
       [30.31620209],
       [39.        ],
       [30.31620209],
       [30.31620209],
       [65.        ],
       [23.        ],
       [30.31620209],
       [22.        ],
       [35.        ],
       [23.        ],
       [18.        ],
       [36.        ],
       [ 9.        ],
       [17.        ],
       [30.31620209],
       [38.        ],
       [17.        ],
       [ 4.        ],
       [45.5       ],
       [23.        ],
       [32.        ],
       [26.        ],
       [ 6.        ],
       [24.        ],
       [45.        ],
       [29.        ],
       [30.31620209],
       [30.31620209],
       [42.        ],
       [36.        ],
       [33.        ],
       [17.        ],
       [29.        ],
       [50.        ],
       [35.        ],
       [38.        ],
       [34.        ],
       [17.        ],
       [11.        ],
       [61.        ],
       [30.        ],
       [ 7.        ],
       [63.        ],
       [20.        ],
       [30.31620209],
       [29.        ],
       [36.        ],
       [30.31620209],
       [50.        ],
       [27.        ],
       [30.        ],
       [33.        ],
       [30.31620209],
       [30.31620209],
       [ 2.        ],
       [25.        ],
       [51.        ],
       [25.        ],
       [30.31620209],
       [30.31620209],
       [24.        ],
       [18.        ],
       [30.31620209],
       [25.        ],
       [24.        ],
       [22.        ],
       [ 0.92      ],
       [24.        ],
       [26.        ],
       [34.        ],
       [21.        ],
       [30.31620209],
       [30.31620209],
       [30.31620209],
       [22.        ],
       [62.        ],
       [18.        ],
       [42.        ],
       [57.        ],
       [19.        ],
       [42.        ],
       [30.31620209],
       [20.        ],
       [34.5       ],
       [28.        ],
       [30.31620209],
       [23.        ],
       [22.        ],
       [52.        ],
       [30.        ],
       [36.5       ],
       [30.31620209],
       [22.        ],
       [50.        ],
       [27.        ],
       [22.        ],
       [51.        ],
       [36.        ],
       [29.        ],
       [22.        ],
       [50.        ],
       [40.        ],
       [27.        ],
       [30.31620209],
       [65.        ],
       [17.        ],
       [28.        ],
       [ 4.        ],
       [30.31620209],
       [ 1.        ],
       [36.        ],
       [43.        ],
       [38.        ],
       [31.        ],
       [29.        ],
       [18.        ],
       [30.31620209],
       [39.        ],
       [39.        ],
       [26.        ],
       [20.        ],
       [30.31620209],
       [49.        ],
       [23.        ],
       [ 1.        ],
       [30.31620209],
       [30.31620209],
       [ 3.        ],
       [ 4.        ],
       [19.        ],
       [40.5       ],
       [ 1.        ],
       [30.31620209],
       [21.        ],
       [54.        ],
       [30.31620209],
       [25.        ],
       [26.        ],
       [22.        ],
       [31.        ],
       [49.        ],
       [19.        ],
       [24.        ],
       [16.        ],
       [25.        ],
       [39.        ],
       [47.        ],
       [60.        ],
       [24.        ],
       [30.31620209],
       [27.        ],
       [30.31620209],
       [38.        ],
       [44.        ],
       [21.        ],
       [24.        ],
       [45.        ],
       [ 8.        ],
       [ 8.        ],
       [30.31620209],
       [32.        ],
       [50.        ],
       [21.        ],
       [50.        ],
       [23.        ],
       [32.        ],
       [30.31620209],
       [21.        ],
       [30.31620209],
       [25.        ],
       [15.        ],
       [31.        ],
       [25.        ],
       [54.        ],
       [28.        ],
       [38.        ],
       [41.        ],
       [33.        ],
       [52.        ],
       [16.        ],
       [20.        ],
       [ 9.        ],
       [30.31620209],
       [30.31620209],
       [30.31620209],
       [54.        ],
       [26.        ],
       [60.        ],
       [30.31620209],
       [44.        ],
       [20.        ],
       [30.31620209],
       [16.        ],
       [43.        ],
       [17.        ],
       [37.        ]])